### ISSUE TITLE
themeAttack and strikerAttack not working

### ISSUE THREAD

**Issue by vrdpulse** [oxygencraft/DebugMod#10]
![e1](https://cloud.githubusercontent.com/assets/27949018/25327864/5096ead2-2908-11e7-9a8b-34d0e9fda9d7.png)

**Comment by oxygencraft** [comment]
Are you on pathfinder 2.0.1? If so, it doesn't work for pathfinder 2.0.1. I'll release 1.7.5b to fix this

**Comment by oxygencraft** [comment]
I also tested this on my end with pathfinder 2.0.1 and it works fine so this is not a bug.

**Comment by oxygencraft** [comment]
1.7.5b has been released to fix issues with Pathfinder 2.0.1. Try 1.7.5b with Pathfinder 2.0.1 before reopening the issue

**Comment by vrdpulse** [comment]
Thank you for the response sir! Since version 1.5 with 2.0 and 2.0.1 of Pathfinder, I'm having a problem with the 2 commands. Now with 1.7.5b, it doesn't load at the start and gives this error. Thank you again for your time.

![e2](https://cloud.githubusercontent.com/assets/27949018/25351171/6c5b1d9a-295a-11e7-8c64-db59ca7d8586.png)

**Comment by oxygencraft** [comment]
This should now be fixed, redownload 1.7.5b.

**Comment by vrdpulse** [comment]
Thank you sir. Still getting the very first problem. Is there a log file where it throws that Exception error that I can upload?

**Comment by oxygencraft** [comment]
Pathfinder issue: https://github.com/Arkhist/Hacknet-Pathfinder/issues/9

**Comment by oxygencraft** [comment]
It's actually on your side, try verify game cache and do the normal stuff when a game is corrupted.
